# Generated by Django 4.0.4 on 2022-05-28 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_body_review_my_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='director',
        ),
    ]
