# Generated by Django 4.0.4 on 2022-05-29 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_movie_director'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='movie',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
